services:
  db:
    image: mysql:8.0.33
    container_name: last_discover_db
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3307:3306"
    volumes:
      - last_discover_data:/var/lib/mysql
      - ./db-init:/docker-entrypoint-initdb.d

volumes:
  last_discover_data:
